import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'package:uuid/uuid.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:intl/intl.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'dart:ui' as ui;
import 'l10n/app_localizations.dart';
import 'src/timer_sound_player.dart';
import 'src/workout_timer_controller.dart';
import 'src/platform/file_share.dart';
import 'src/platform/kv_store.dart';
import 'src/platform/sync.dart';
import 'src/platform/telegram.dart';
import 'src/spike_screen.dart';

part 'src/iron_vibe_part_core.dart';
part 'src/iron_vibe_part_theme.dart';
part 'src/iron_vibe_part_models.dart';
part 'src/iron_vibe_part_muscle_groups.dart';
part 'src/iron_vibe_part_widgets.dart';
part 'src/iron_vibe_part_progress.dart';
part 'src/iron_vibe_part_personal_progress.dart';
part 'src/iron_vibe_part_favorite_exercises.dart';
part 'src/iron_vibe_part_app.dart';
part 'src/iron_vibe_part_instructions.dart';
part 'src/iron_vibe_part_backup.dart';
part 'src/iron_vibe_part_trainer.dart';
part 'src/iron_vibe_part_session_print.dart';
part 'src/iron_vibe_part_rhythm.dart';
part 'src/iron_vibe_part_rhythm_insight.dart';
part 'src/iron_vibe_part_athlete.dart';
